name: PR Review Action Notification

on:
  pull_request_review:
    types:
      - submitted

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification on PR Approved
        id: telegram
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          REVIEW_USER="${{ github.event.review.user.login }}"
          PR_ACTION="approved"
          MESSAGE_THREAD_ID="2"  # El ID del hilo del mensaje que deseas usar

          if [ "$PR_ACTION" == "approved" ]; then
            MESSAGE="APPROVED!!%0A%0ARepository: J1Connect.%0APR Title: $PR_TITLE.%0APR Author: $PR_AUTHOR.%0AReview by: $REVIEW_USER.%0APR URL: $PR_URL"
          fi

          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=$MESSAGE" \
          -d "message_thread_id=$MESSAGE_THREAD_ID"

  commented:
    if: github.event.review.state == 'commented' && github.event.review.body != null
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification on PR Commented
        id: telegram
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          REVIEW_USER="${{ github.event.review.user.login }}"
          COMMENT="${{ github.event.review.body }}"
          PR_ACTION="commented"
          MESSAGE_THREAD_ID="2"  # El ID del hilo del mensaje que deseas usar

          if [ "$PR_ACTION" == "commented" ]; then
            MESSAGE="COMMENTED!!%0A%0ARepository: J1Connect.%0APR Title: $PR_TITLE.%0APR Author: $PR_AUTHOR.%0AReview by: $REVIEW_USER.%0AComment: $COMMENT.%0APR URL: $PR_URL"
          fi

          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=$MESSAGE" \
          -d "message_thread_id=$MESSAGE_THREAD_ID"

  changes_requested:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification on PR Changes Requested
        id: telegram
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          REVIEW_USER="${{ github.event.review.user.login }}"
          PR_ACTION="changes_requested"
          MESSAGE_THREAD_ID="2"  # El ID del hilo del mensaje que deseas usar

          if [ "$PR_ACTION" == "changes_requested" ]; then
            MESSAGE="CHANGES REQUESTED!!%0A%0ARepository: J1Connect.%0APR Title: $PR_TITLE.%0APR Author: $PR_AUTHOR.%0AReview by: $REVIEW_USER.%0APR URL: $PR_URL"
          fi

          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=$MESSAGE" \
          -d "message_thread_id=$MESSAGE_THREAD_ID"
