name: PR Review Request Notification

on:
  pull_request:
    types:
      - review_requested
      - ready_for_review
    branches:
      - main
      - staging

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification on PR Action
        id: telegram
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_ACTION="${{ github.event.action }}"
          PR_ACTION_UPPER="${PR_ACTION^^}"
          REVIEWER="${{ github.event.requested_reviewer.login }}"
          MESSAGE_THREAD_ID="2"

          if [ "$PR_ACTION" == "review_requested" ]; then
            MESSAGE="$PR_ACTION_UPPER!!%0A%0APR Title: $PR_TITLE.%0APR Author: $PR_AUTHOR.%0AReview By: $REVIEWER.%0APR URL: $PR_URL"
          elif [ "$PR_ACTION" == "ready_for_review" ]; then
            MESSAGE="$PR_ACTION_UPPER!!%0A%0APR Title: $PR_TITLE.%0APR Author: $PR_AUTHOR.%0AReview By: $REVIEWER.%0APR URL: $PR_URL"
          fi

          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=$MESSAGE" \
          -d "message_thread_id=$MESSAGE_THREAD_ID"
